### ISSUE TITLE
How to redirect directly to my matrix room?

### ISSUE THREAD

**Issue by NIXOYE** [Josue-T/riot_ynh#1]
Hi, I've installed Riot through Yunohost and I'd like visitors to the subdomain it is hosted on to be redirected automatically to my specific room on Matrix. How can I achieve this?

**Comment by Josue-T** [comment]
Hello,
I think it depends if riot is public or not. If it is public you can just get the url when you are on your chattrom with riot and add the link to this url.

**Comment by NIXOYE** [comment]
It is public. What do you mean by add the link to this url?

On May 31, 2017 2:14 AM, "Josue-T" <notifications@github.com> wrote:

Hello,
I think it depends if riot is public or not. If it is public you can just
get the url when you are on your chattrom with riot and add the link to
this url.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Josue-T/riot_ynh/issues/1#issuecomment-305094183>, or mute
the thread

**Comment by Josue-T** [comment]
Yes, but I never tried. You should try.

**Comment by NIXOYE** [comment]
I'm not sure what your asking me to try

**Comment by Josue-T** [comment]
Juste get the url like this : `https://domain.tld/riot/#/room/#room:server.tld`

**Comment by NIXOYE** [comment]
Then what?

**Comment by Josue-T** [comment]
Sorry, but I think I didn't have really understand your question... Sorry

**Comment by NIXOYE** [comment]
I want visitors to my website sub.domain.tld to be sent to
https://sub.domain.tld/riot/#/room/%23room:server.tld

**Comment by Josue-T** [comment]
When he click on a url ?

**Comment by NIXOYE** [comment]
When they type it.
¿Hablas español?

**Comment by Josue-T** [comment]
Sorry, but I really don't understand what you mean. I think if your problem is about riot and not the package for yunohost it's better to ask the question to the riot community. I'm not a specialist of riot and matrix. I'm just a packager for yunohost.

**Comment by NIXOYE** [comment]
I want to edit the nginx setup in the package so it automatically redirects
but I don't know which nginx file to edit

**Comment by Josue-T** [comment]
Ok, the nginx config file for riot is here : `/etc/nginx/conf.d/domain.tld.d/riot.conf`
